# Generated by Django 5.2 on 2025-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlextractionresult',
            name='extracted_merchant_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
