# Generated by Django 5.2 on 2025-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_mlextractionresult_extracted_merchant_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
    ]
